version: '3.7'

services:

  nailsDash:
    image: nails-web
    container_name: nails-web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:80
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
